//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetic2.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EvolutionEntities : DbContext
    {
        public EvolutionEntities()
            : base("name=EvolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FamilyTree> FamilyTrees { get; set; }
    
        public virtual ObjectResult<GenerationsBeforeSuccess_Result> GenerationsBeforeSuccess()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerationsBeforeSuccess_Result>("GenerationsBeforeSuccess");
        }
    
        public virtual ObjectResult<GraphData_Result> GraphData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GraphData_Result>("GraphData");
        }
    }
}
