//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetic2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyTree
    {
        public long Generation { get; set; }
        public int Child { get; set; }
        public long RunTime { get; set; }
        public long LinesOfCode { get; set; }
        public long Score { get; set; }
        public bool WasSuccessful { get; set; }
    }
}
